# Generated by Django 3.2 on 2022-03-23 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactthread',
            name='user',
        ),
        migrations.DeleteModel(
            name='ContactMessage',
        ),
        migrations.DeleteModel(
            name='ContactThread',
        ),
    ]
