# Generated by Django 3.2 on 2022-03-23 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0002_auto_20220323_2045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='description',
            field=models.TextField(max_length=200),
        ),
        migrations.AlterField(
            model_name='request',
            name='destination',
            field=models.CharField(max_length=50),
        ),
    ]
