# Generated by Django 3.2 on 2022-02-14 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0002_request_approved'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='duration',
        ),
    ]
