# Generated by Django 3.2 on 2022-03-24 13:19

from django.db import migrations, models
import trips.validators


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0004_alter_review_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='description',
            field=models.TextField(max_length=200, validators=[trips.validators.validate_comment]),
        ),
        migrations.AlterField(
            model_name='request',
            name='destination',
            field=models.CharField(max_length=50, validators=[trips.validators.validate_comment]),
        ),
    ]
